# Generated by Django 6.0.6 on 2026-06-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClonedRepository',
            fields=[
                ('repo_url', models.URLField(max_length=500, primary_key=True, serialize=False)),
                ('local_path', models.CharField(max_length=500)),
                ('repo_map', models.JSONField(blank=True, null=True)),
                ('primary_language', models.CharField(blank=True, max_length=50, null=True)),
                ('cloned_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
